version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: c-dev-environment
    volumes:
      - .:/home/bigsky033
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "15213:15213"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    tmpfs:
      - /tmp:exec
    environment:
      - DISPLAY=${DISPLAY:-:0}
    stdin_open: true
    tty: true
