# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

export LANG=en_US.UTF-8

plugins=(
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
	tmux
)


# Add applications to path
export PATH=$PATH:$HOME/Applications

# neovim
alias vi="nvim"
alias vim="nvim"
alias view="nvim -R"
alias vimdiff="nvim -d"

# tmux
ZSH_TMUX_AUTOSTART=true

# golang
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
export PATH=$PATH:${GOPATH}/bin
export PATH=$PATH:/usr/local/go/bin

# node
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# oh my zsh
source $ZSH/oh-my-zsh.sh

# xclip
alias pbcopy='xclip -selection clipboard'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# python
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"

# java
# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

neofetch
